version: '3.8'

services:
    gateway-app:
        build: Backend\gateway-app
        container_name: gateway-app
        ports:
            - "8080:8080"
        restart: unless-stopped
        networks:
            - scoring-model-network
            - backend-network
            - webscraper-network
        
        environment:
            - WEB_API_URL=http://web-api:8081
            - SCORING_MODEL_URL=http://scoring-model:80

    web-api:
        build: Backend\web-api
        container_name: web-api
        restart: unless-stopped
        networks:
            - backend-network
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - JWT_KEY=${JWT_KEY}
            - JWT_EXPIRATION=${JWT_EXPIRATION}
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}
            - GATEWAY_URL = http://gateway-app:8080

    scoring-model:
        build: ModelScoringowy
        container_name: scoring-model
        restart: unless-stopped
        networks:
            - scoring-model-network