version: '3.8'

services:
    gateway-app:
        build: Backend\gateway-app
        container_name: gateway-app
        ports:
            - "8080:8080"
        restart: unless-stopped
        networks:
            - scoring-model-network
            - backend-network
            - webscraper-network
        
        environment:
            - WEB_API_URL=http://web-api:8081

    web-api:
        build: Backend\web-api
        container_name: web-api
        restart: unless-stopped
        networks:
            - backend-network
        


networks:
    scoring-model-network:
        driver: bridge
    
    backend-network:
        driver: bridge
    
    webscraper-network:
        driver: bridge