### Add offers from csv to database
POST http://localhost:8080/api/offer/add

### Get map points with filters
POST http://localhost:8080/api/offer/map-points
Content-Type: application/json

{
  "roomsFrom": 7
}

### Get map points without filters
POST http://localhost:8080/api/offer/map-points
Content-Type: application/json
{}

### Get filter ranges
GET http://localhost:8080/api/offer/offer-filter-ranges

### Show offer details
GET http://localhost:8080/api/offer/show?offerId=686

### Get prediction
GET http://localhost:8080/api/offer/predict-price/1